name: odyssee
description: Odyssee Application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  google_maps_flutter: 0.5.24+1 
  flutter_svg: ^0.12.1
  path_provider:
  path:
  gpx: ^0.0.1
  flutter_polyline_points: ^0.1.0
  location: ^2.3.5
  latlong: ^0.6.1
  webview_flutter: ^0.3.14+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.4+1
  firebase_storage: ^3.1.3
  cloud_functions: ^0.4.2+3
  provider: ^3.1.0
  flutter_spinkit: ^4.0.0

  # for tflite
  image_picker: ^0.6.3+4
  image: ^2.1.4
  tflite: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/models/odyssee/model_v2.tflite
   - assets/models/odyssee/labels_imagenet_slim.txt
   - assets/nature.jpg
   - assets/icons/
   - assets/images/
   - assets/images/rep_images/
   - assets/gpx/

  fonts:
    - family: Kiri
      fonts:
        - asset: fonts/KiriFont.ttf
    - family: Orkney
      fonts:
        - asset: fonts/Orkney Regular.ttf
    - family: BOTW
      fonts:
        - asset: fonts/BOTW.ttf
